ENT.Base = "npc_vj_creature_base"
ENT.Type = "ai"
ENT.PrintName = "Zombie"
ENT.Author = "An average Beanmann"
ENT.Contact = ""
-- ENT.Information = "Faction: Zombies\nRank: Fodder\n\nMoves faster when close enough to an enemy.\nCan sometimes spawn with a Headcrab and/or as a Splitter.\nIf it has a Headcrab, the crab can randomly detatch itself when an enemy is close enough.\nIf it's a Splitter, it has a random chance to split when damaged.\nLeg shots cause it to split and become a Torso.\nChest, Head, and Arm shots cause it to split and become Legs.\nStomach shots and hitgroupless damage cause it to pick between Torso, Legs, or Both.\nExplosions have a greater chance to cause splits.\n"
ENT.Information = "Standard Zombie.\nCan spawn with a Headcrab and/or as a Splitter.\nSplitters might split when shot or hit by an explosion.\nMoves faster at close range.\n"
ENT.Category = "Bean's Sourcey Zombies"
ENT.VJ_ID_Undead = true